devices([
  "iPhone 16 Pro Max",
  "iPhone 16 Pro",
  "iPhone 16",
  "iPhone 15 Pro Max",
  "iPhone 15 Pro",
  "iPhone 14 Pro Max",
  "iPhone 14 Pro"
])

languages([
  "en-US",
  "hi-IN"
])

output_directory("./fastlane/screenshots")
clear_previous_screenshots(true)
