import { Router, type IRouter } from "express";
import healthRouter from "./health";
import paymentsRouter from "./payments";
import authRouter from "./auth";
import kycRouter from "./kyc";
import accountRouter from "./account";
import otpConfigRouter from "./otp-config";
import paymentConfigRouter from "./payment-config";
import callsRouter from "./calls";
import feedRouter from "./feed";
import usersRouter from "./users";
import chatRouter from "./chat";
import adminAuthRouter from "./admin-auth";
import pkBattleRouter from "./pk-battle";
import analyticsConfigRouter from "./analytics-config";
import downloadsRouter from "./downloads";
import moderateRouter from "./moderate";
import friendRequestsRouter from "./friend_requests";
import walletRouter from "./wallet";
import plansRouter from "./plans";

const router: IRouter = Router();

router.use(healthRouter);
router.use(paymentsRouter);
router.use(authRouter);
router.use(kycRouter);
router.use(accountRouter);
router.use(otpConfigRouter);
router.use(paymentConfigRouter);
router.use(callsRouter);
router.use(feedRouter);
router.use(usersRouter);
router.use(chatRouter);
router.use(adminAuthRouter);
router.use(pkBattleRouter);
router.use(analyticsConfigRouter);
router.use(downloadsRouter);
router.use(moderateRouter);
router.use(friendRequestsRouter);
router.use(walletRouter);
router.use(plansRouter);

export default router;
