// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/voice-reels/Current.tsx": () => import("../components/mockups/voice-reels/Current.tsx"),
  "./components/mockups/voice-reels/Editing.tsx": () => import("../components/mockups/voice-reels/Editing.tsx"),
  "./components/mockups/voice-reels/Music.tsx": () => import("../components/mockups/voice-reels/Music.tsx"),
  "./components/mockups/voice-reels/Themes.tsx": () => import("../components/mockups/voice-reels/Themes.tsx")
};
